name: Deploy to Itch.io

env:
  GODOT_VERSION: 4.1.1
  ITCH_PROJECT_NAME: "entangledexplorer"
  ITCH_USERNAME: "SimonR99"
  BUTLER_API_KEY: ${{ secrets.ITCH_IO_API_KEY }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install Missing Libraries
        run: |
          apt-get update && apt-get install -y libxcursor1 libxinerama1 libxrandr2 libxi6 libx11-xcb1

      - name: Install and Setup Xvfb
        run: |
          apt-get update && apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Move Export Templates
        run: |
          mkdir -p /github/home/.local/share/godot/export_templates/4.1.1.stable
          mv /root/.local/share/godot/templates/4.1.1.stable/* /github/home/.local/share/godot/export_templates/4.1.1.stable
        
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --export-release "Web" ./build/web/index.html || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web

  push-to-itch:
    needs: export-web
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: web
          path: build/web

      - name: Download + Authorize Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Login To Butler
        run: ./butler login

      - name: Push to Itch.io
        run: ./butler push build/web $ITCH_USERNAME/$ITCH_PROJECT_NAME:web
